#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x01FABCC83FEA225E (release-signing@dino.im)
#
Name     : dino
Version  : 0.3.1
Release  : 11
URL      : https://github.com/dino/dino/releases/download/v0.3.1/dino-0.3.1.tar.gz
Source0  : https://github.com/dino/dino/releases/download/v0.3.1/dino-0.3.1.tar.gz
Source1  : https://github.com/dino/dino/releases/download/v0.3.1/dino-0.3.1.tar.gz.asc
Summary  : Modern XMPP ("Jabber") Chat Client using GTK+/Vala
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : buildreq-cmake
BuildRequires : gettext-dev
BuildRequires : git
BuildRequires : gnutls-dev
BuildRequires : libgcrypt-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gee-0.8)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libsignal-protocol-c)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : qrencode-dev
BuildRequires : vala

%description
![Dino](https://dino.im/img/readme_header.svg)
=======
![screenshots](https://dino.im/img/screenshot-main.png)

%prep
%setup -q -n dino-0.3.1
cd %{_builddir}/dino-0.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672168889
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make
popd

%install
export SOURCE_DATE_EPOCH=1672168889
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dino
cp %{_builddir}/dino-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/dino/31a3d460bb3c7d98845187c716a30db81c44b615
pushd clr-build
%make_install
popd
## install_append content
# these plugins are statically linked now...
#mkdir -p %{buildroot}/usr/lib64
#install clr-build/libcrypto-vala.so clr-build/libgpgme-vala.so clr-build/libsignal-protocol-vala.so %{buildroot}/usr/lib64
## install_append end

%files
%defattr(-,root,root,-)
