#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x01FABCC83FEA225E (release-signing@dino.im)
#
Name     : dino
Version  : 0.2.0
Release  : 7
URL      : https://github.com/dino/dino/releases/download/v0.2.0/dino-0.2.0.tar.gz
Source0  : https://github.com/dino/dino/releases/download/v0.2.0/dino-0.2.0.tar.gz
Source1  : https://github.com/dino/dino/releases/download/v0.2.0/dino-0.2.0.tar.gz.asc
Summary  : Modern XMPP ("Jabber") Chat Client using GTK+/Vala
Group    : Development/Tools
License  : GPL-3.0
Requires: dino-bin = %{version}-%{release}
Requires: dino-data = %{version}-%{release}
Requires: dino-lib = %{version}-%{release}
Requires: dino-license = %{version}-%{release}
Requires: dino-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : gettext-dev
BuildRequires : git
BuildRequires : gpgme-dev
BuildRequires : libgcrypt-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gee-0.8)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libsignal-protocol-c)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : qrencode-dev
BuildRequires : vala

%description
![Dino](https://dino.im/img/readme_header.svg)
=======
![screenshots](https://dino.im/img/screenshot-main.png)

%package bin
Summary: bin components for the dino package.
Group: Binaries
Requires: dino-data = %{version}-%{release}
Requires: dino-license = %{version}-%{release}

%description bin
bin components for the dino package.


%package data
Summary: data components for the dino package.
Group: Data

%description data
data components for the dino package.


%package dev
Summary: dev components for the dino package.
Group: Development
Requires: dino-lib = %{version}-%{release}
Requires: dino-bin = %{version}-%{release}
Requires: dino-data = %{version}-%{release}
Provides: dino-devel = %{version}-%{release}
Requires: dino = %{version}-%{release}

%description dev
dev components for the dino package.


%package lib
Summary: lib components for the dino package.
Group: Libraries
Requires: dino-data = %{version}-%{release}
Requires: dino-license = %{version}-%{release}

%description lib
lib components for the dino package.


%package license
Summary: license components for the dino package.
Group: Default

%description license
license components for the dino package.


%package locales
Summary: locales components for the dino package.
Group: Default

%description locales
locales components for the dino package.


%prep
%setup -q -n dino-0.2.0
cd %{_builddir}/dino-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605578489
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make
popd

%install
export SOURCE_DATE_EPOCH=1605578489
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dino
cp %{_builddir}/dino-0.2.0/LICENSE %{buildroot}/usr/share/package-licenses/dino/1de7bacb4fbbd7b6d391a69abfe174c2509ec303
pushd clr-build
%make_install
popd
%find_lang dino-omemo
%find_lang dino-openpgp
%find_lang dino
## install_append content
mkdir -p %{buildroot}/usr/lib64
install clr-build/libcrypto-vala.so clr-build/libgpgme-vala.so clr-build/libsignal-protocol-vala.so %{buildroot}/usr/lib64
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dino

%files data
%defattr(-,root,root,-)
/usr/share/applications/im.dino.Dino.desktop
/usr/share/dbus-1/services/im.dino.Dino.service
/usr/share/icons/hicolor/scalable/apps/im.dino.Dino.svg
/usr/share/icons/hicolor/scalable/status/dino-changes-prevent-symbolic.svg
/usr/share/icons/hicolor/scalable/status/dino-double-tick-symbolic.svg
/usr/share/icons/hicolor/scalable/status/dino-qr-code-symbolic.svg
/usr/share/icons/hicolor/scalable/status/dino-status-away.svg
/usr/share/icons/hicolor/scalable/status/dino-status-chat.svg
/usr/share/icons/hicolor/scalable/status/dino-status-dnd.svg
/usr/share/icons/hicolor/scalable/status/dino-status-online.svg
/usr/share/icons/hicolor/scalable/status/dino-tick-symbolic.svg
/usr/share/icons/hicolor/symbolic/apps/im.dino.Dino-symbolic.svg
/usr/share/metainfo/im.dino.Dino.appdata.xml
/usr/share/vala/vapi/dino.deps
/usr/share/vala/vapi/dino.vapi
/usr/share/vala/vapi/qlite.deps
/usr/share/vala/vapi/qlite.vapi
/usr/share/vala/vapi/xmpp-vala.deps
/usr/share/vala/vapi/xmpp-vala.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/dino.h
/usr/include/dino_i18n.h
/usr/include/qlite.h
/usr/include/xmpp-vala.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/dino/plugins/http-files.so
/usr/lib64/dino/plugins/omemo.so
/usr/lib64/dino/plugins/openpgp.so
/usr/lib64/libcrypto-vala.so
/usr/lib64/libdino.so
/usr/lib64/libdino.so.0
/usr/lib64/libdino.so.0.0
/usr/lib64/libgpgme-vala.so
/usr/lib64/libqlite.so
/usr/lib64/libqlite.so.0
/usr/lib64/libqlite.so.0.1
/usr/lib64/libsignal-protocol-vala.so
/usr/lib64/libxmpp-vala.so
/usr/lib64/libxmpp-vala.so.0
/usr/lib64/libxmpp-vala.so.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dino/1de7bacb4fbbd7b6d391a69abfe174c2509ec303

%files locales -f dino-omemo.lang -f dino-openpgp.lang -f dino.lang
%defattr(-,root,root,-)

